#!/bin/bash
aws ec2 create-vpc \
 --region us-east-1 \
 --cidr-block  192.168.1.194/23 \
 --query 'VPC.Vpcid' \
 --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=RaviVpc}]' \
 --output text
